### ISSUE TITLE
Give proper credits

### ISSUE THREAD

**Issue by sergey-alekseev** [rubymem/ruby-mem-advisory-db#5]
Currently README.md [mentions](https://github.com/rubymem/ruby-mem-advisory-db/tree/231688afecc6877c3f0bc2b6fd4d28a1d8169d77#credits) a legacy [CONTRIBUTORS.md](https://github.com/rubymem/ruby-mem-advisory-db/blob/d21d675b209e5f8c0f08290965b23a3d0e0ef411/CONTRIBUTORS.md). May be mention contributors from https://github.com/ASoftCo/leaky-gems#contributors and the list itself. The list [refers]((https://github.com/ASoftCo/leaky-gems/commit/4ada5c1ed00af86603e05259e606d3735cdd5a53)) to the gem now.

**Comment by sergey-alekseev** [comment]
Looks like at least one contributor is still missing... 😉

**Comment by etagwerker** [comment]
@sergey-alekseev Good point! Thanks for the heads up and sorry about that.

**Comment by bronzdoc** [comment]
Closed in https://github.com/rubymem/ruby-mem-advisory-db/pull/12
