### ISSUE TITLE
Leak: net-http-persistent 3.0.0

### ISSUE THREAD

**Issue by zealot128** [rubymem/ruby-mem-advisory-db#6]
It's a dependency of mechanize, which is quite popular:

https://github.com/drbrain/net-http-persistent/pull/98

https://github.com/sparklemotion/mechanize/issues/528

- present in: 3.0.0
- Fixed in: v3.1.0 v3.0.1

**Comment by etagwerker** [comment]
@zealot128 thanks for sharing! Do you wanna take it one step further and submit a PR? 😊
